# Generated by Django 5.1.4 on 2025-02-15 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='null', max_length=255)),
                ('score', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('correct_choice', models.CharField(default='null', max_length=255)),
                ('last_choice', models.CharField(default='null', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_name', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(upload_to='posters/')),
            ],
        ),
        migrations.CreateModel(
            name='SongTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, unique=True)),
                ('album', models.CharField(default='', max_length=255)),
                ('lyrics', models.TextField(default='')),
                ('poster_pics', models.ManyToManyField(blank=True, related_name='song_titles', to='ts.poster')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='songs/')),
                ('song_title', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ts.songtitle')),
            ],
        ),
    ]
