# Generated by Django 5.1.3 on 2024-12-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0002_songtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='songtitle',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
