# Generated by Django 5.1.4 on 2025-03-12 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0002_gamehistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='player_name',
        ),
    ]
