# Generated by Django 5.1.3 on 2024-12-03 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0003_gamehistory_alter_songtitle_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='song_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ts.songtitle'),
        ),
        migrations.AddField(
            model_name='songtitle',
            name='poster_pic',
            field=models.ImageField(default='posters/default.jpg', upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='songtitle',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
