# Generated by Django 5.1.4 on 2025-03-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0003_remove_gamehistory_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_file_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
