# Generated by Django 5.1.4 on 2025-03-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0004_song_original_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
