# Generated by Django 5.2.5 on 2025-08-22 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0005_gamehistory_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('in_progress', 'In Progress'), ('revealing', 'Revealing'), ('ended', 'Ended')], db_index=True, default='in_progress', max_length=16)),
                ('score', models.PositiveIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('max_turns', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GameTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveIntegerField()),
                ('correct_option', models.CharField(max_length=255)),
                ('selected_option', models.CharField(blank=True, max_length=255, null=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('correct', 'Correct'), ('wrong', 'Wrong'), ('timeout', 'Timeout')], db_index=True, default='pending', max_length=10)),
                ('snippet_start_sec', models.PositiveIntegerField(default=0)),
                ('time_limit_secs', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='ts.gamesession')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turns', to='ts.song')),
            ],
            options={
                'ordering': ('session', 'sequence_index'),
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ts.gameturn'),
        ),
        migrations.AddIndex(
            model_name='gameturn',
            index=models.Index(fields=['session', 'outcome'], name='ts_gameturn_session_dd1477_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameturn',
            unique_together={('session', 'sequence_index')},
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['user', 'status'], name='ts_gamesess_user_id_1cb9e1_idx'),
        ),
    ]
