# Generated by Django 5.1.3 on 2024-12-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0006_songtitle_album_songtitle_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ts.songtitle'),
        ),
    ]
