# Generated by Django 5.2.5 on 2025-08-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0006_gamesession_gameturn_gamesession_current_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameturn',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
