# Generated by Django 5.2.5 on 2025-08-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0007_gameturn_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameturn',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
