# Generated by Django 5.2.5 on 2025-09-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0008_gameturn_poster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='max_turns',
        ),
    ]
