# Generated by Django 5.1.3 on 2024-12-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0009_alter_song_file_alter_songtitle_poster_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2012-01-01'),
            preserve_default=False,
        ),
    ]
