# Generated by Django 5.2.5 on 2025-09-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0009_remove_gamesession_max_turns'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='health',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
