# Generated by Django 5.1.3 on 2024-12-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0010_gamehistory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='player_name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
