# Generated by Django 5.2.5 on 2025-10-07 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0010_gamesession_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='next_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ts.gameturn'),
        ),
    ]
