# Generated by Django 5.1.3 on 2024-12-10 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0011_gamehistory_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamehistory',
            old_name='timestamp',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='end_time',
            field=models.DateField(default='2012-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='wrong_song',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ts.songtitle'),
        ),
    ]
