# Generated by Django 5.1.3 on 2024-12-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0013_alter_gamehistory_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='wrong_song',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='last_choice',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
