# Generated by Django 5.1.3 on 2024-12-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0014_remove_gamehistory_wrong_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='correct_choice',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
